### ISSUE TITLE
Images missing on filter

### ISSUE THREAD

**Issue by teacii** [princemaple/img-src-ondemand#7]
Hi,

I love the addon and thank you for it.
I request assistance with the following:

Situation:
I am showing a long list of articles with thumbnail pic on the left.
When I filter, the list becomes smaller as expected.

Problem:
Lets say I type a word in the filter and there are only two matches.
If the the match is an article from the lower part of the list, the pic does not get loaded.

Remark:
If i just scroll thru the list, all pics appear, lazy loading as they should.

Any suggestions would be welcome.

Thanks
TeaCii

**Comment by princemaple** [comment]
Hi @teacii , glad you like this.
Some time ago I created a new module that covers everything this one does and more.
Check it out at https://github.com/princemaple/scroll-trigger
Using this new module, you can programmatically call updates on the service, e.g. call it when you have new inputs on your filter variable.
FYI I only intend the maintain `scroll-trigger` in the future.

Po

**Comment by princemaple** [comment]
Going to close this, feel free to reopen or open another issue on https://github.com/princemaple/scroll-trigger
